### ISSUE TITLE
update method is missing from crud log

### ISSUE THREAD

**Issue by mrgoos** [soynatan/django-easy-audit#128]
Hi,
I've noticed that when I use [update](https://docs.djangoproject.com/en/2.2/topics/db/queries/#updating-multiple-objects-at-once) method, I don't see a matching record in `easyaudit_crudevent` table.
Why is this and how can I overcome it?

I read that:
`
Django Easy Audit uses Django signals to listen to the events happening in your project, such as when a user creates, updates or deletes a registry.
`
And we know that update method:
`
Be aware that the update() method is converted directly to an SQL statement. It is a bulk operation for direct updates. It doesn’t run any save() methods on your models, or emit the pre_save or post_save signals
`
So I'm mostly interested in how to overcome it, obviously we have many updates in the code.
I'm using version 1.1 but about to upgrade.
Thanks.

**Comment by jheld** [comment]
In django 2.2 bulk_update was created, and that could help for bulk operations, assuming the result set isn't enormous (can fit in memory); there are strategies for the latter which we can discuss but let's not focus on that.

If you take the objects you get from filter, apply your bulk_update and then you could emulate the CRUDEvent signal logic by hand and that probably would work.

I would like to expose the important logic pieces of CRUDEvent such that an application can use it in the case of bulk_create and bulk_update.

We don't have that yet but I can see that a few projects would likely leverage it!

The actual issue with filter.update itself is that the standard practices of relational databases that are given internal programmatic updates is that the number of rows (and thus which rows) which are supposed to be updated are not known ahead of time. So once the update goes through it returns how many rows which were updated -- not the primary/composite keys themselves. As such filter.update for the standard SQL flows will thus be unable to feed into the django model signals. The model signals rely on individual concrete operations and thus the signals work!

bulk_update would work (with some code changes/logic explosing) because we _know_ which objects we're updating because we are passing them into bulk_update.

Let me know what you think of this!

**Comment by mrgoos** [comment]
@jheld - thanks for your response and sorry for the delay :)
Bottom line - you're saying that if we'll replace our updates with `bulk_update` it'd work?

**Comment by jheld** [comment]
That does sound correct. `easyaudit` should try to provide a programmatic public interface to expose the flow for `CRUDEvent` bulk_creation support, via accepting an iterable of objects that are/were changed. `pre_save` and `post_save` still are not used in that `QuerySet` API, so there may still be other concerns/edge cases/possible known bugs (how do we generate/resolve the changed_fields etc), but other than that, currently it seems like a worthwhile experiment/branch/test at the least.

**Comment by mrgoos** [comment]
Thanks, I'll dig in it.
But you have to admin that if `CRUDEvent` are allegedly supported it's really unexpected that `update`, which is as you wrote, the U in CRUD - is not supported.
WDYT?

**Comment by jheld** [comment]
Any limitations that django has, we do too. The way django implements update has a limitation which is based on the design of how SQL servers (mysql, postgresql) do update-based statements (they return the count of the number of rows updated, so dynamic join and where clauses mean that we cannot always guarantee that we know exactly what was changed. Some of this is discussed in the django docs, and probably near the link I shared earlier). So if you do single/individual saves of objects, that will result in CRUDEvent with event type update, if the save is updating the object.

I'm happy to discuss it further and/or link to more relevant documentation, but as far as django and this framework are concerned, this is the best we can do with the current technology (and without relying on binlog/replication log replays, which would then likely be implemented outside of django/python in some form anyway).

So, we will ignore `R` in CRUD for now, but so long as you want to use django 100% to get the support for multiple update `U`, it cannot be done/well-defined/fully in python. `bulk_update` does not natively solve the problem, but since it requires an iterable of known/resolved objects to update (as opposed to a standard where clause which may/usually implies dynamic queries), my hunch is that we can hook into that flow to give easyaudit more powers.

**Comment by jheld** [comment]
Closing this issue since the direct problem is not specific to easy audit (and not even truly a django problem). We should make a new issue specific to bulk create and bulk update support.

**Comment by johnnymetz** [comment]
Has audit logging on bulk operations, e.g. `bulk_create`, `bulk_update` been implemented. I think a context manager is a fantastic idea. Someone in a related django project had a similar strategy: https://github.com/jazzband/django-auditlog/issues/240

**Comment by jheld** [comment]
It has not been. The design I was considering has only been put into as much detail here as you've seen, although I still believe the complexity won't balloon (e.g. the problem space, via napkin math, IMO can be an evolution of our current code with the public API being the guts, and the/a context manager, for instance, being the code entry/flow semantics, at a sufficiently high-enough level for every day use).
