### ISSUE TITLE
Problem when saving date time field fails to audit the change

### ISSUE THREAD

**Issue by arjun-vs** [soynatan/django-easy-audit#132]
In my project i need to track a change in datetime field whenever a change in date time field occur easy audit crashes with m2m exception. 
 easy audit had an m2m-changed exception.
 Traceback (most recent call last):
  File "/code/easyaudit/signals/model_signals.py", line 215, in m2m_changed
   object_json_repr = serializers.serialize("json", [instance])
   File "/usr/local/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
  s.serialize(queryset, **options)
   File "/usr/local/lib/python3.8/site-packages/django/core/serializers/base.py", line 107, in serialize
    self.handle_field(obj, field)
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/python.py", line 49, in handle_field
   self._current[field.name] = self._value_from_field(obj, field)
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/python.py", line 46, in _value_from_field
   return value if is_protected_type(value) else field.value_to_string(obj)
 File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1381, in value_to_string
   return '' if val is None else val.isoformat()
AttributeError: 'str' object has no attribute 'isoformat'

how to resolve this error...?

**Comment by arjun-vs** [comment]
after changing the date time field value to None it start auditing again.

**Comment by henribru** [comment]
I just hit this issue as well. Seems related to https://code.djangoproject.com/ticket/28356. Basically, the problem is that it's legal to save strings to a `DateField`/`DateTimeField` and when you retrieve the object from the database again you'll get a `date`/`datetime`. But before you refresh it or retrieve it again the field will contain a string and it will crash upon serialization.

**Comment by jheld** [comment]
My assumption is that one of the only things we can do is, before sending the instance into serialization (1 element list), we can loop through the fields of the instance's model, and for any which are date/datetime, we should convert them to their type, then serialize.

If we think that will suffice and be correct, I don't think it will be hard to do.

**Comment by jheld** [comment]
Any takers? I may be able to do it, but it will likely be at least a week before I can try.

**Comment by jsoa** [comment]
@jheld @arjun-vs 
TBH, i agree with django marking the issue as `wontfix`. I don't think it should be the responsibility of easy audit to change model data to meet the type needed for serialization. It should be the consumer of easy-audit's responsibility, imo

Here is roughly what we might have to do
- loop over all the instance fields
- find the date types we need to convert (from `_meta.fields`)
- take into account naive vs tz aware dates
- parse it
- set them on the instance
- serialize it. 

Seems like a a lot for easy-audit to do, when saving it with the correct type (as django suggests) fixes this issue

**Comment by henribru** [comment]
I would argue that it *is* easy-audit's responsibility to be able to record legitimate changes you can do to a Django model, since that's kinda the point of the library. That it does so by using Django's built-in serialization, which doesn't handle this case, is really just an implementation detail. As long as saving strings to a DateTimeField is something Django can handle (which it can, what they `wontfix` is just serializing it directly afterwards without reloading it from the database), it's quite unexpected for easy-audit to crash on it.

I agree that it's a lot to fix a pretty narrow edge case though, so I understand that it might not be worth the trouble.

**Comment by jheld** [comment]
It's not the responsibility of this library to fix this. Django is taking a hard stance (it's realistic, but brutal).

Should we try to be nice to the user? Probably. We agree on what the steps should be - perhaps this "fix" should be a settings toggle, since there are projects where they would likely prefer to be on the hook for any data issues (and don't want the library to make the decision).

There is also an open issue or PR here I think related to having a custom serializer hook, seems like a great time to look into that because it likely solves this (people can opt in to fix it themselves!).

**Comment by arjun-vs** [comment]
Actually i had written my own class for solving the problem.. anyway thanks for ur all ur contributions on the same.

**Comment by mschoettle** [comment]
Running into this issue as well. In particular when creating a model instance using `Model.objects.create(some_date_field='2023-07-05')` (in our case it's during tests where we use `factory-boy`).

Since `Manager.create` does not trigger a `clean_fields` the date string is not converted to a `date`.

It would be possible to call `clean_fields` in the signal but not sure if this is ideal.

**Comment by samamorgan** [comment]
> I would argue that it _is_ easy-audit's responsibility to be able to record legitimate changes you can do to a Django model, since that's kinda the point of the library. That it does so by using Django's built-in serialization, which doesn't handle this case, is really just an implementation detail. As long as saving strings to a DateTimeField is something Django can handle (which it can, what they `wontfix` is just serializing it directly afterwards without reloading it from the database), it's quite unexpected for easy-audit to crash on it.
> 
> I agree that it's a lot to fix a pretty narrow edge case though, so I understand that it might not be worth the trouble.

Totally agree with this. This is eady-audit's responsibility to fix. This package is using Django's model serialization in a way it was not intended to be used (against unsaved instances) and running across this issue. This is a clear bug in this library that needs to be fixed.

The fix is pretty simple too. Just iterate all model fields and call `to_python` on date/time fields. Does anyone have any objections to me putting up a PR for this?
