### ISSUE TITLE
Save READ actions?

### ISSUE THREAD

**Issue by Puciek** [soynatan/django-easy-audit#14]
It would be awesome if we could also include R in the Crud actions log, for those who need complete auditing setup ;).

**Comment by soynatan** [comment]
Thank you for your suggestion. I explored this possibility before but I haven't found the right approach yet.

This app uses Django signals to work. Unfortunately, there's no signal for when you are getting a queryset (for example, in a `ListView`). However, there's a `post_init` signal that could be used to log when an object is instatiated. I think this could be useful to log when an object is being read in a `DetailView`.

The problem with this, is that if in any place of your code you need to instatiate a model object (for whatever reason), it would generate a log entry too. This would lead to a lot of "wrong" read events.

Another approach would be to use a [mixin class](https://docs.djangoproject.com/en/1.10/topics/class-based-views/mixins/), that you would have to add to your `ListView`s and `DetailView`s. I'm not a fan of this idea, since it would take away the simplicity of the app, which can be installed/uninstalled without changing anything in your apps' code.

Maybe there's another way I'm missing (probably), so I'ill keep this issue open. Thank you again!

**Comment by Puciek** [comment]
@soynatan I wound up going another way about it, as we didn't need saving read on models directly, as much as we needed logging of what people access. And since they only access it through the web interface/api I wrote it over `request_started` signal.

If you are curious have a look,: https://github.com/soynatan/django-easy-audit/compare/master...Puciek:master and if you are interested in pulling it in I will polish it up and put it up as a proper pull request. I've also added logging of remote_ip with requests and login/out actions.

**Comment by soynatan** [comment]
This looks interesting! First of all, I'm sorry for not getting back at you with this sooner. It looks like a good idea to use this signal to log R events. But again, maybe I'm missing something. I would like @jheld and @KatrinaE input on this.

A PR is welcome if you have some time to work on it (beware that the base has changed since you posted this). I'm wondering whether R events should be logged by default or not, since on some projects that is going to mean a lot of data. But that's debatable.

**Comment by jheld** [comment]
@soynatan @Puciek I do like this idea. My team is probably going to need the `R` events in the near future. I was just going to put the onus on the views...but this is not a bad idea at all, and gets out of the consuming project's way.

I would like to be able to specify url roots (and possibly even specific regex), though, because for instance, I wouldn't necessarily want `/admin/` to get hit by this. For us it's mostly through an API and thus even our internal team would generate lots of hits (this is my assumption, without testing).

On the flip-side, just tagging the URL path etc doesn't technically mark which objects were read, just which view was called (implicitly). If the view has special logic to determine which data is read/returned, given the moon-cycle, then one could argue that at one point an object was read, and at one point it wasn't, but with just the URL it is harder to argue it.

Then again...that's a really advanced case, and one that this project cannot help with at all.

I do like the implementation you have so far @Puciek; I only took a couple minutes with it, but again, pretty good!

**Comment by Puciek** [comment]
@jheld @soynatan hey guys, sorry for the late response, busy week over here!

And maybe a good idea for the exclusion is a support for white/blacklist of regexp patterns, this way deciding which URLs to log and to not log is a matter of setting up appropriate setting?

And I am glad that you like the implementation, I will try to spend a bit more time on it soon, rebase it to match current master and present it as a PR.

**Comment by soynatan** [comment]
Great!

> On the flip-side, just tagging the URL path etc doesn't technically mark which objects were read

Yes, I don't see a clear way to log which object/s were read just from logging the URL. Maybe, adding some logic to the views, as you suggest. I guess we can explore this later, when request logging is already working.

> maybe a good idea for the exclusion is a support for white/blacklist of regexp patterns, this way deciding which URLs to log and to not log is a matter of setting up appropriate setting?

Yes, I think that we should log every request by default, and have a setting to avoid some url patterns, and another setting to turn on/off requests auditing.

Thank you both so much!

**Comment by soynatan** [comment]
[A branch was created](https://github.com/soynatan/django-easy-audit/tree/feat/log-requests) to which you can merge when you have something on this. Thank you!

**Comment by soynatan** [comment]
So, I ended up coding it myself. It is 99% @Puciek's code. I excluded the feature to log the remote IP, for now. You can check it out in [save-read-events](https://github.com/soynatan/django-easy-audit/tree/save-read-events) branch.

Right now it works, but it's not very useful. For example, not only it logs every request on the admin pages, but also, it logs every request to static files. So, opening a simple page will generate tons of RequestEvent entries (because of CSS, JS, SVG, PNG, fonts, etc.).

I will implement a black/white list as soon as I can.

**Comment by soynatan** [comment]
I added a few settings to control this behaviour. Now it's possible to list regex patterns of URLs that shouldn't be logged. By default, it won't log anything under `/admin/` or `/static/`, but that can be overwritten or extended.

I made some other changes, like separating the signal handlers in different modules, and a little more. I should start documenting all the settings in the wiki.
