### ISSUE TITLE
http post body data to RequestEvent

### ISSUE THREAD

**Issue by zhengyscn** [soynatan/django-easy-audit#145]
http post body data to RequestEvent

**Comment by jheld** [comment]
We may be open to it but it likely would need some configuration/settings.

Not every project will want to audit/store this, and some payloads can be quite large (and others just "not small"). I think it would be a better idea for a plugin to be leveraged with this. We now have pluggable backend support, so we theoretically could extend the contract of the request event API to pass the data through, and the active backend can simply choose to ignore it.

Thoughts?

**Comment by jheld** [comment]
I'm going to close this since the request is likely not a small undertaking. Please open a new issue or PR for extensions to the RequestEvent backend flow logic/contract. We are open to it but it would likely be better to have a more fine tuned issue created against it (it can reference this issue for history).
