### ISSUE TITLE
Why is CRUD_DIFFERENCE_CALLBACKS not considered in should_audit?

### ISSUE THREAD

**Issue by MaehMaeh** [soynatan/django-easy-audit#195]
Question:
In the signals `pre_save` and `post_save` `should_audit` is called at the beginning. But in this function only `UNREGISTERED_CLASSES` and `REGISTERED_CLASSES` are considered. Wouldn't it make more sense to consider `CRUD_DIFFERENCE_CALLBACKS` there as well?

**Comment by jheld** [comment]
These ended up being developed at very different times and likely different view points of what was being accomplished. 

The callbacks function is intended for flexibility and allows the developer to inspect the db/object state and perform whatever logic they need. It also must be run as close to crud object creation as possible so that the crud repr is processed.

The should function runs very early on and I agree that the name is misleading with regards to the other one. I would recommend that if a change is to be made, it would be on the function naming to make it more clear. Comments also help.

**Comment by MaehMaeh** [comment]
Thank you for the explanation. 

My thought was to write the tables to be monitored into a database table, which I can then read out with a callback function. This would allow me to set the tables a bit more dynamically. But apparently the intended way is to go through the Django settings.
