### ISSUE TITLE
New model not being audited

### ISSUE THREAD

**Issue by dekhaus** [soynatan/django-easy-audit#32]
Hi

I added easy-audit to my app and the one existing model (Survey) was successfully being audited.

I then added another model (Result).  That model is not being audited.  What do I need to do so that easy-audit audits the Result model (and any other models I add) ?

Thanks
Dave

**Comment by soynatan** [comment]
Hello, dekhaus. easy-audit should log everything by default (unless you [configure](https://github.com/soynatan/django-easy-audit#settings) it otherwise), be it an existing or new model.

Sometimes, when this problem occurs, it has to do with how your model is converted to string. Please, check whether you have defined a `__str__` or `__unicode__` method, or both, in the model which is causing problem. If so, try removing those methods, and see if easy audit works then.

Try that and tell me how it went. Thanks.

**Comment by dekhaus** [comment]
Hi

Figured out why it wasn't working.  The primary key of my new table Result was a UUID.  EasyAudit was throwing an exception because the UUID once converted to an integer was really big (like 64 bits big).

Rather than creation a custom migration to alter the easyaudit_crudevent table - I just changed the Result's primary key to a simple integer.

Now it works

Dave

**Comment by soynatan** [comment]
Glad you figured it out.

Happy coding!
