### ISSUE TITLE
Release new version to PyPI

### ISSUE THREAD

**Issue by dapicester** [soynatan/django-easy-audit#49]
Hi, I was just opening an issue about cookie when I just found that the master branch already fixed that. So I would like to ask if it is possible to release a new version to PyPI so we get it from there instead of manually get a zip out of Github.

**Comment by jheld** [comment]
HI @dapicester another option is for you to build the wheel yourself internally and use that in your `requirements.txt`. We realize that isn't the most native solution, but it will at least be recognized well by PIP in the meantime.

However, yes, we will want to update PyPI. With #50 we might want to put those together, so we don't have too many release updates all at once.

@soynatan thoughts?

**Comment by soynatan** [comment]
@jheld yeah, I wanted to close some of the bigger issues (i.e. #29 and #38) before releasing a new version to PyPi, but I don't think that's gonna happen soon, so maybe we can close #50 and do it.

Also, on #51 you suggested that maybe there was a simpler way to store the changed fields. You think you can work on that before releasing to PyPi? If not, we'll leave it for another future version.

**Comment by jheld** [comment]
@soynatan I think I understand what they were doing on #51 . They were taking the current value (from db) and comparing it to what will be the new value (what will be saved). Makes sense.

I was going to compare the full json repr from the previous CRUD against the one we're about to save. I see why they did, and I'm hoping the bug I'm seeing on my [attempt to] update is not related to it...but haven't yet determined that. If it's because of that, do you think my CRUD diff would work? My team has a `dict_compare` method which I could push into the repo for this purpose. It returns a tuple like the following:

`(added, modified, removed)`, where each is a `{}`, such that `field_name: (previous, current)`. This is partly from my memory, so I'll be sure it gives the right format. And I'd try to make it the same format as what #51 implemented. That is, if there really is a bug in pre-save.

I'll let you know as soon as I find out. But I don't necessarily want to hold up the release.

**Comment by ishirav** [comment]
Hi, it would be great if you could release a new version. v1.0 is from more than half a year ago, and I see that some significant progress had been made since. Thanks!

**Comment by harrywhite4** [comment]
Any updates on this? i am also encountering some issues which seem to have been fixed already. Happy to help out if needed

**Comment by jheld** [comment]
I will plan to release one or more versions to github next week. As far as PyPI releases...I don't have that power. I would rather not create a secondary project on there just yet.

**Comment by jheld** [comment]
We have a new release on github, but still awaiting PyPI. So, if you're willing to point to github for version, as opposed to PyPI (github link in requirements.txt), then that should work for the time being.

**Comment by harrywhite4** [comment]
Thanks for that. I was installing from master, but il switch to the 1.1 tag instead

**Comment by soynatan** [comment]
Hello, sorry for my absence. Version 1.1 has been uploaded to PyPi. Thank you.
