### ISSUE TITLE
Why the username and id?

### ISSUE THREAD

**Issue by gileadslostson** [soynatan/django-easy-audit#7]
Did you have a specific reason for doing so or was it convenience?

**Comment by soynatan** [comment]
Are you referring to the LoginEvent model? It stores both the username and the id because:

* When the user fails to log in, there will be no user object, hence no id, so you need to store the string.

* Besides, if the user failed to log in, it could be because the username was miswritten (not just the password). Storing the username string allows you to log exactly how the username was written.

* Another reason is that usernames could be changed, or more so, the user could be deleted. So logging what the username was at that moment could be useful.

If you were referrring to something else please let me know.

**Comment by gileadslostson** [comment]
Nope, that was it! Sorry I wasn't more clear, and thanks for the answer.

Awesome project.

**Comment by soynatan** [comment]
Perfect, thank you for your interest. Kudos!
